let img;
let c1;
let c2;
let c3;
let c4;
let c5;
let c6;
let c7;
let c8;
function preload(){
img = loadImage("https://i.insider.com/5627b552dd0895ee6a8b4666?width=1009&format=jpeg");
}

function setup(){
    createCanvas(img.width,img.height);
        background(255)
c1 = PosX

        for(PosX = 1; PosX  < img.width; PosX + 3 ){
   for(PosY = 1; PosY < img.height; PosxY + 3 ){





        }   
    }
}

function draw(){
    image(img,0,0);
}